#!/bin/sh

set -e

# rpm/deb packages
if [ -e "/usr/local/share/kubits" ]; then
    KUBITS_HOME="/usr/local/share/kubits"
# running out of git checkout
else
    KUBITS_HOME=$( cd "$(dirname "$0")" ; pwd -P )
fi

# homebrew (macos) installations will set this to an absolute path during installation:
export KUBECTL_PLUGINS_PATH="${KUBITS_HOME}/kubectl-plugins/tail"
exec kubectl plugin tail "$@"
